
CC=gcc

CFLAGS = -Wall -std=c99

all: dhanesh eric ganesh anji


dhanesh:
	${CC} ${CFLAGS} dhanesh.c -o dhanesh


eric:
	${CC} ${CFLAGS} eric.c -o eric

ganesh:
	${CC} ${CFLAGS} ganesh.c -o ganesh

anji:
	${CC} ${CFLAGS} anji.c -o anji

clean:
	rm -rf dhanesh eric ganesh anji
